gems: [jekyll-paginate, jekyll-coffeescript]
exclude: ['TODO', 'Gemfile.lock', 'Gemfile']
url: https://heipei.net
title: heipei - Jojo
name: heipei
description: Jojo
paginate: 4
paginate_path: "/page/:num/"
